
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class TbStartZone : Singleton<TbStartZone>, IConfig
    {
        private readonly Dictionary<int, TbStartZoneRow> _dataMap;
        private readonly List<TbStartZoneRow> _dataList;

        public TbStartZone(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbStartZoneRow>();
            _dataList = new List<TbStartZoneRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbStartZoneRow _v;
                _v = TbStartZoneRow.DeserializeStartZoneConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbStartZoneRow> DataMap => _dataMap;
        public List<TbStartZoneRow> DataList => _dataList;

        public TbStartZoneRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbStartZoneRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
