
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 效果操作类型
    /// </summary>
    public enum EffectActionType
    {
        None = 0,

        /// <summary>
        /// 比如：当前血量、当前蓝量，改变时会判定上限，最小0
        /// </summary>
        ChangePropertyReal = 2,

        /// <summary>
        /// 攻击力百分比+固定值
        /// </summary>
        Healing = 3,

        /// <summary>
        /// 攻击力百分比+固定值
        /// </summary>
        Damage = 4,

        /// <summary>
        /// 添加Buff
        /// </summary>
        AddBuff = 5,

        /// <summary>
        /// 移除Buff
        /// </summary>
        RemoveBuff = 6,

        /// <summary>
        /// 添加限制
        /// </summary>
        AddRestrict = 7,

        /// <summary>
        /// 移除限制
        /// </summary>
        RemoveRestrict = 8,

        /// <summary>
        /// 增加子属性的值
        /// </summary>
        AddProperty = 9,

        /// <summary>
        /// 降低子属性的值
        /// </summary>
        SubProperty = 10,

        /// <summary>
        /// 召唤士兵
        /// </summary>
        SummonSoldier = 11,

        /// <summary>
        /// 随机召唤
        /// </summary>
        SummonRandom = 12,

        /// <summary>
        /// 杀死自己
        /// </summary>
        KillSelf = 13,

        /// <summary>
        /// 以0索敌，执行1效果组
        /// </summary>
        Research = 15,

        /// <summary>
        /// 判定条件0，通过执行1效果组，否则执行2效果组
        /// </summary>
        ConditionBranch = 16,

        /// <summary>
        /// 跟随目标直到命中
        /// </summary>
        AddBulletTarget = 17,

        /// <summary>
        /// 朝指定位置发射子弹
        /// </summary>
        AddBulletPosition = 18,

        /// <summary>
        /// 朝指定的方向发射子弹
        /// </summary>
        AddBulletDirection = 19,

    }
}
