
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 索敌类型
    /// </summary>
    public enum ESearchTargetTeam
    {
        None = 0,

        /// <summary>
        /// 自己
        /// </summary>
        Self = 1,

        /// <summary>
        /// 友方含自己
        /// </summary>
        Friend = 2,

        /// <summary>
        /// 友方不含自己
        /// </summary>
        FriendExcludeSelf = 3,

        /// <summary>
        /// 敌方队伍
        /// </summary>
        Enemy = 4,

        /// <summary>
        /// 反击
        /// </summary>
        Counter = 6,

        /// <summary>
        /// 全体
        /// </summary>
        All = 7,

        /// <summary>
        /// 全局
        /// </summary>
        Global = 8,

        /// <summary>
        /// 友方全局
        /// </summary>
        FriendTeam = 9,

        /// <summary>
        /// 敌方全局
        /// </summary>
        EnemyTeam = 10,

    }
}
