
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 效果类型
    /// </summary>
    public enum ESkillEffectType
    {
        None = 0,

        /// <summary>
        /// 实时属性改变
        /// </summary>
        ChangePropertyReal = 2,

        /// <summary>
        /// 攻击力百分比+固定值
        /// </summary>
        Healing = 3,

        /// <summary>
        /// 攻击力百分比+固定值
        /// </summary>
        Damage = 4,

        /// <summary>
        /// 添加Buff
        /// </summary>
        AddBuff = 5,

        /// <summary>
        /// 移除Buff
        /// </summary>
        RemoveBuff = 6,

        /// <summary>
        /// 添加限制
        /// </summary>
        AddRestrict = 7,

        /// <summary>
        /// 移除限制
        /// </summary>
        RemoveRestrict = 8,

        /// <summary>
        /// 增加属性
        /// </summary>
        AddProperty = 9,

        /// <summary>
        /// 降低属性
        /// </summary>
        SubProperty = 10,

        /// <summary>
        /// 召唤士兵
        /// </summary>
        SummonSoldier = 11,

        /// <summary>
        /// 随机召唤
        /// </summary>
        SummonRandom = 12,

        /// <summary>
        /// 目标子弹
        /// </summary>
        AddBulletTarget = 13,

        /// <summary>
        /// 位置子弹
        /// </summary>
        AddBulletPosition = 14,

        /// <summary>
        /// 重新索敌
        /// </summary>
        Research = 15,

    }
}
