
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 效果类型
    /// </summary>
    public enum ESkillEffectType
    {
        None = 0,

        /// <summary>
        /// 属性改变
        /// </summary>
        ChangeProperty = 1,

        /// <summary>
        /// 实时属性改变
        /// </summary>
        ChangePropertyReal = 2,

        /// <summary>
        /// 攻击力百分比+固定值
        /// </summary>
        Healing = 3,

        /// <summary>
        /// 攻击力百分比+固定值
        /// </summary>
        Damage = 4,

        /// <summary>
        /// 添加Buff
        /// </summary>
        AddBuff = 5,

        /// <summary>
        /// 添加子弹
        /// </summary>
        AddBullet = 6,

        /// <summary>
        /// 添加限制
        /// </summary>
        AddRestrict = 7,

        /// <summary>
        /// 移除Buff
        /// </summary>
        RemoveBuff = 9,

        /// <summary>
        /// 召唤士兵
        /// </summary>
        SummonSoldier = 10,

        /// <summary>
        /// 生产掉落
        /// </summary>
        GenDrop = 11,

        /// <summary>
        /// 重新索敌
        /// </summary>
        Research = 12,

    }
}
