
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 禁止标签
    /// </summary>
    [System.Flags]
    public enum FlagRestrict
    {
        None = 0,

        /// <summary>
        /// 禁止移动
        /// </summary>
        NotMove = 1,

        /// <summary>
        /// 禁止普通技能
        /// </summary>
        NotAttack = 2,

        /// <summary>
        /// 禁止主动技能
        /// </summary>
        NotActive = 4,

        /// <summary>
        /// 禁止AI警戒
        /// </summary>
        NotAIAlert = 8,

        /// <summary>
        /// 禁止旋转
        /// </summary>
        NotRotate = 16,

    }
}
