
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    /// <summary>
    /// 掉落组Item
    /// </summary>
    [EnableClass]
    public sealed partial class ItemRandomSet : BeanBase
    {
        public ItemRandomSet(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Weight = _buf.ReadInt();
            Type = (EUnitType)_buf.ReadInt();
            CountMin = _buf.ReadInt();
            CountMax = _buf.ReadInt();

            PostInit();
        }

        public static ItemRandomSet DeserializeItemRandomSet(ByteBuf _buf)
        {
            return new ItemRandomSet(_buf);
        }

        /// <summary>
        /// 产出ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 产出权重
        /// </summary>
        public readonly int Weight;

        /// <summary>
        /// 产出类型
        /// </summary>
        public readonly EUnitType Type;

        /// <summary>
        /// 最小个数
        /// </summary>
        public readonly int CountMin;

        /// <summary>
        /// 最大个数
        /// </summary>
        public readonly int CountMax;


        public const int __ID__ = -2022039892;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "weight:" + Weight + ","
            + "type:" + Type + ","
            + "countMin:" + CountMin + ","
            + "countMax:" + CountMax + ","
            + "}";
        }

        partial void PostInit();
    }
}
