
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 属性类型
    /// </summary>
    public enum NumericType
    {
        /// <summary>
        /// 血量
        /// </summary>
        Hp = 1,

        /// <summary>
        /// 蓝量
        /// </summary>
        Mp = 2,

        /// <summary>
        /// 属性ID区间：10000~99999
        /// </summary>
        Max = 10000,

        /// <summary>
        /// 生命值
        /// </summary>
        MaxHp = 1001,

        /// <summary>
        /// 生命值B
        /// </summary>
        MaxHpBase = 10011,

        /// <summary>
        /// 生命值BD
        /// </summary>
        MaxHpBaseAdd = 10012,

        /// <summary>
        /// 生命值BP
        /// </summary>
        MaxHpBasePct = 10013,

        /// <summary>
        /// 生命值FD
        /// </summary>
        MaxHpFinalAdd = 10014,

        /// <summary>
        /// 生命值FP
        /// </summary>
        MaxHpFinalPct = 10015,

        /// <summary>
        /// 魔法值
        /// </summary>
        MaxMp = 1002,

        /// <summary>
        /// 魔法值B
        /// </summary>
        MaxMpBase = 10021,

        /// <summary>
        /// 魔法值BD
        /// </summary>
        MaxMpBaseAdd = 10022,

        /// <summary>
        /// 魔法值BP
        /// </summary>
        MaxMpBasePct = 10023,

        /// <summary>
        /// 魔法值FD
        /// </summary>
        MaxMpFinalAdd = 10024,

        /// <summary>
        /// 魔法值FP
        /// </summary>
        MaxMpFinalPct = 10025,

        /// <summary>
        /// 攻击力
        /// </summary>
        Atk = 1003,

        /// <summary>
        /// 攻击力B
        /// </summary>
        AtkBase = 10031,

        /// <summary>
        /// 攻击力BD
        /// </summary>
        AtkBaseAdd = 10032,

        /// <summary>
        /// 攻击力BP
        /// </summary>
        AtkBasePct = 10033,

        /// <summary>
        /// 攻击力FD
        /// </summary>
        AtkFinalAdd = 10034,

        /// <summary>
        /// 攻击力FP
        /// </summary>
        AtkFinalPct = 10035,

        /// <summary>
        /// 防御力
        /// </summary>
        Def = 1004,

        /// <summary>
        /// 防御力B
        /// </summary>
        DefBase = 10041,

        /// <summary>
        /// 防御力BD
        /// </summary>
        DefBaseAdd = 10042,

        /// <summary>
        /// 防御力BP
        /// </summary>
        DefBasePct = 10043,

        /// <summary>
        /// 防御力FD
        /// </summary>
        DefFinalAdd = 10044,

        /// <summary>
        /// 防御力FP
        /// </summary>
        DefFinalPct = 10045,

        /// <summary>
        /// 速度
        /// </summary>
        Speed = 1005,

        /// <summary>
        /// 速度B
        /// </summary>
        SpeedBase = 10051,

        /// <summary>
        /// 速度BD
        /// </summary>
        SpeedBaseAdd = 10052,

        /// <summary>
        /// 速度BP
        /// </summary>
        SpeedBasePct = 10053,

        /// <summary>
        /// 速度FD
        /// </summary>
        SpeedFinalAdd = 10054,

        /// <summary>
        /// 速度FP
        /// </summary>
        SpeedFinalPct = 10055,

        /// <summary>
        /// AOI值
        /// </summary>
        AOI = 1006,

        /// <summary>
        /// AOI值B
        /// </summary>
        AOIBase = 10061,

        /// <summary>
        /// AOI值BD
        /// </summary>
        AOIBaseAdd = 10062,

        /// <summary>
        /// AOI值BP
        /// </summary>
        AOIBasePct = 10063,

        /// <summary>
        /// AOI值FD
        /// </summary>
        AOIFinalAdd = 10064,

        /// <summary>
        /// AOI值FP
        /// </summary>
        AOIFinalPct = 10065,

        /// <summary>
        /// 攻速
        /// </summary>
        AtkSpeed = 1007,

        /// <summary>
        /// 攻速B
        /// </summary>
        AtkSpeedBase = 10071,

        /// <summary>
        /// 攻速BD
        /// </summary>
        AtkSpeedBaseAdd = 10072,

        /// <summary>
        /// 攻速BP
        /// </summary>
        AtkSpeedBasePct = 10073,

        /// <summary>
        /// 攻速FD
        /// </summary>
        AtkSpeedFinalAdd = 10074,

        /// <summary>
        /// 攻速FP
        /// </summary>
        AtkSpeedFinalPct = 10075,

    }
}
