
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 属性类型
    /// </summary>
    public enum NumericType
    {
        None = 0,

        /// <summary>
        /// 血量
        /// </summary>
        Hp = 1,

        /// <summary>
        /// 蓝量
        /// </summary>
        Mp = 2,

        /// <summary>
        /// 金币
        /// </summary>
        Gold = 100,

        /// <summary>
        /// 木材
        /// </summary>
        Wood = 101,

        /// <summary>
        /// 人口
        /// </summary>
        Population = 102,

        /// <summary>
        /// 增加普攻目标
        /// </summary>
        AddNormalTargetCount = 501,

        /// <summary>
        /// 分隔特殊约定属性 1~499区间内的属性加1000对应他的最大值属性
        /// </summary>
        SpecialMax = 500,

        /// <summary>
        /// 分隔父子属性 10000~99999区间内的属性变化时都要更新其父属性
        /// </summary>
        Max = 10000,

        /// <summary>
        /// 生命值
        /// </summary>
        MaxHp = 1001,

        /// <summary>
        /// 生命值B
        /// </summary>
        MaxHpBase = 10011,

        /// <summary>
        /// 生命值BD
        /// </summary>
        MaxHpBaseAdd = 10012,

        /// <summary>
        /// 生命值BP
        /// </summary>
        MaxHpBasePct = 10013,

        /// <summary>
        /// 生命值FD
        /// </summary>
        MaxHpFinalAdd = 10014,

        /// <summary>
        /// 生命值FP
        /// </summary>
        MaxHpFinalPct = 10015,

        /// <summary>
        /// 魔法值
        /// </summary>
        MaxMp = 1002,

        /// <summary>
        /// 魔法值B
        /// </summary>
        MaxMpBase = 10021,

        /// <summary>
        /// 魔法值BD
        /// </summary>
        MaxMpBaseAdd = 10022,

        /// <summary>
        /// 魔法值BP
        /// </summary>
        MaxMpBasePct = 10023,

        /// <summary>
        /// 魔法值FD
        /// </summary>
        MaxMpFinalAdd = 10024,

        /// <summary>
        /// 魔法值FP
        /// </summary>
        MaxMpFinalPct = 10025,

        /// <summary>
        /// 攻击力
        /// </summary>
        Atk = 1003,

        /// <summary>
        /// 攻击力B
        /// </summary>
        AtkBase = 10031,

        /// <summary>
        /// 攻击力BD
        /// </summary>
        AtkBaseAdd = 10032,

        /// <summary>
        /// 攻击力BP
        /// </summary>
        AtkBasePct = 10033,

        /// <summary>
        /// 攻击力FD
        /// </summary>
        AtkFinalAdd = 10034,

        /// <summary>
        /// 攻击力FP
        /// </summary>
        AtkFinalPct = 10035,

        /// <summary>
        /// 防御力
        /// </summary>
        Def = 1004,

        /// <summary>
        /// 防御力B
        /// </summary>
        DefBase = 10041,

        /// <summary>
        /// 防御力BD
        /// </summary>
        DefBaseAdd = 10042,

        /// <summary>
        /// 防御力BP
        /// </summary>
        DefBasePct = 10043,

        /// <summary>
        /// 防御力FD
        /// </summary>
        DefFinalAdd = 10044,

        /// <summary>
        /// 防御力FP
        /// </summary>
        DefFinalPct = 10045,

        /// <summary>
        /// 速度
        /// </summary>
        Speed = 1005,

        /// <summary>
        /// 速度B
        /// </summary>
        SpeedBase = 10051,

        /// <summary>
        /// 速度BD
        /// </summary>
        SpeedBaseAdd = 10052,

        /// <summary>
        /// 速度BP
        /// </summary>
        SpeedBasePct = 10053,

        /// <summary>
        /// 速度FD
        /// </summary>
        SpeedFinalAdd = 10054,

        /// <summary>
        /// 速度FP
        /// </summary>
        SpeedFinalPct = 10055,

        /// <summary>
        /// AOI值
        /// </summary>
        AOI = 1006,

        /// <summary>
        /// AOI值B
        /// </summary>
        AOIBase = 10061,

        /// <summary>
        /// AOI值BD
        /// </summary>
        AOIBaseAdd = 10062,

        /// <summary>
        /// AOI值BP
        /// </summary>
        AOIBasePct = 10063,

        /// <summary>
        /// AOI值FD
        /// </summary>
        AOIFinalAdd = 10064,

        /// <summary>
        /// AOI值FP
        /// </summary>
        AOIFinalPct = 10065,

        /// <summary>
        /// 攻速
        /// </summary>
        AtkSpeed = 1007,

        /// <summary>
        /// 攻速B
        /// </summary>
        AtkSpeedBase = 10071,

        /// <summary>
        /// 攻速BD
        /// </summary>
        AtkSpeedBaseAdd = 10072,

        /// <summary>
        /// 攻速BP
        /// </summary>
        AtkSpeedBasePct = 10073,

        /// <summary>
        /// 攻速FD
        /// </summary>
        AtkSpeedFinalAdd = 10074,

        /// <summary>
        /// 攻速FP
        /// </summary>
        AtkSpeedFinalPct = 10075,

        /// <summary>
        /// 攻击距离
        /// </summary>
        AtkRange = 1008,

        /// <summary>
        /// 攻击距离B
        /// </summary>
        AtkRangeBase = 10081,

        /// <summary>
        /// 攻击距离BD
        /// </summary>
        AtkRangeBaseAdd = 10082,

        /// <summary>
        /// 攻击距离BP
        /// </summary>
        AtkRangeBasePct = 10083,

        /// <summary>
        /// 攻击距离FD
        /// </summary>
        AtkRangeFinalAdd = 10084,

        /// <summary>
        /// 攻击距离FP
        /// </summary>
        AtkRangeFinalPct = 10085,

        /// <summary>
        /// 暴击率
        /// </summary>
        CriticalRate = 1009,

        /// <summary>
        /// 暴击率B
        /// </summary>
        CriticalRateBase = 10091,

        /// <summary>
        /// 暴击率BD
        /// </summary>
        CriticalRateBaseAdd = 10092,

        /// <summary>
        /// 暴击率BP
        /// </summary>
        CriticalRateBasePct = 10093,

        /// <summary>
        /// 暴击率FD
        /// </summary>
        CriticalRateFinalAdd = 10094,

        /// <summary>
        /// 暴击率FP
        /// </summary>
        CriticalRateFinalPct = 10095,

        /// <summary>
        /// 暴击伤害比例
        /// </summary>
        CriticalDamagePercent = 1010,

        /// <summary>
        /// 暴击伤害比例B
        /// </summary>
        CriticalDamagePercentBase = 10101,

        /// <summary>
        /// 暴击伤害比例BD
        /// </summary>
        CriticalDamagePercentBaseAdd = 10102,

        /// <summary>
        /// 暴击伤害比例BP
        /// </summary>
        CriticalDamagePercentBasePct = 10103,

        /// <summary>
        /// 暴击伤害比例FD
        /// </summary>
        CriticalDamagePercentFinalAdd = 10104,

        /// <summary>
        /// 暴击伤害比例FP
        /// </summary>
        CriticalDamagePercentFinalPct = 10105,

        /// <summary>
        /// 反弹伤害比例
        /// </summary>
        ReboundDamagePercent = 1011,

        /// <summary>
        /// 反弹伤害比例B
        /// </summary>
        ReboundDamagePercentBaseRate = 10111,

        /// <summary>
        /// 反弹伤害比例BD
        /// </summary>
        ReboundDamagePercentBaseAddRate = 10112,

        /// <summary>
        /// 反弹伤害比例BP
        /// </summary>
        ReboundDamagePercentBasePctRate = 10113,

        /// <summary>
        /// 反弹伤害比例FD
        /// </summary>
        ReboundDamagePercentFinalAddRate = 10114,

        /// <summary>
        /// 反弹伤害比例FP
        /// </summary>
        ReboundDamagePercentFinalPctRate = 10115,

        /// <summary>
        /// 格挡率
        /// </summary>
        BlockRate = 1012,

        /// <summary>
        /// 格挡率B
        /// </summary>
        BlockRateBase = 10121,

        /// <summary>
        /// 格挡率BD
        /// </summary>
        BlockRateBaseAdd = 10122,

        /// <summary>
        /// 格挡率BP
        /// </summary>
        BlockRateBasePct = 10123,

        /// <summary>
        /// 格挡率FD
        /// </summary>
        BlockRateFinalAdd = 10124,

        /// <summary>
        /// 格挡率FP
        /// </summary>
        BlockRateFinalPct = 10125,

        /// <summary>
        /// 格挡伤害比例
        /// </summary>
        BlockDamagePercent = 1013,

        /// <summary>
        /// 格挡伤害比例B
        /// </summary>
        BlockDamagePercentBase = 10131,

        /// <summary>
        /// 格挡伤害比例BD
        /// </summary>
        BlockDamagePercentBaseAdd = 10132,

        /// <summary>
        /// 格挡伤害比例BP
        /// </summary>
        BlockDamagePercentBasePct = 10133,

        /// <summary>
        /// 格挡伤害比例FD
        /// </summary>
        BlockDamagePercentFinalAdd = 10134,

        /// <summary>
        /// 格挡伤害比例FP
        /// </summary>
        BlockDamagePercentFinalPct = 10135,

        /// <summary>
        /// 闪避率
        /// </summary>
        EvasionRate = 1014,

        /// <summary>
        /// 闪避率B
        /// </summary>
        EvasionRateBase = 10141,

        /// <summary>
        /// 闪避率BD
        /// </summary>
        EvasionRateBaseAdd = 10142,

        /// <summary>
        /// 闪避率BP
        /// </summary>
        EvasionRateBasePct = 10143,

        /// <summary>
        /// 闪避率FD
        /// </summary>
        EvasionRateFinalAdd = 10144,

        /// <summary>
        /// 闪避率FP
        /// </summary>
        EvasionRateFinalPct = 10145,

        /// <summary>
        /// 反击率
        /// </summary>
        CounterRate = 1015,

        /// <summary>
        /// 反击率B
        /// </summary>
        CounterRateBase = 10151,

        /// <summary>
        /// 反击率BD
        /// </summary>
        CounterRateBaseAdd = 10152,

        /// <summary>
        /// 反击率BP
        /// </summary>
        CounterRateBasePct = 10153,

        /// <summary>
        /// 反击率FD
        /// </summary>
        CounterRateFinalAdd = 10154,

        /// <summary>
        /// 反击率FP
        /// </summary>
        CounterRateFinalPct = 10155,

        /// <summary>
        /// 金币上限
        /// </summary>
        MaxGold = 1100,

        /// <summary>
        /// 金币上限B
        /// </summary>
        MaxGoldBase = 11001,

        /// <summary>
        /// 金币上限BD
        /// </summary>
        MaxGoldBaseAdd = 11002,

        /// <summary>
        /// 金币上限BP
        /// </summary>
        MaxGoldBasePct = 11003,

        /// <summary>
        /// 金币上限FD
        /// </summary>
        MaxGoldFinalAdd = 11004,

        /// <summary>
        /// 金币上限FP
        /// </summary>
        MaxGoldFinalPct = 11005,

        /// <summary>
        /// 木材上限
        /// </summary>
        MaxWood = 1101,

        /// <summary>
        /// 木材上限B
        /// </summary>
        MaxWoodBase = 11011,

        /// <summary>
        /// 木材上限BD
        /// </summary>
        MaxWoodBaseAdd = 11012,

        /// <summary>
        /// 木材上限BP
        /// </summary>
        MaxWoodBasePct = 11013,

        /// <summary>
        /// 木材上限FD
        /// </summary>
        MaxWoodFinalAdd = 11014,

        /// <summary>
        /// 木材上限FP
        /// </summary>
        MaxWoodFinalPct = 11015,

        /// <summary>
        /// 人口上限
        /// </summary>
        MaxPopulation = 1102,

        /// <summary>
        /// 人口上限B
        /// </summary>
        MaxPopulationBase = 11021,

        /// <summary>
        /// 人口上限BD
        /// </summary>
        MaxPopulationBaseAdd = 11022,

        /// <summary>
        /// 人口上限BP
        /// </summary>
        MaxPopulationBasePct = 11023,

        /// <summary>
        /// 人口上限FD
        /// </summary>
        MaxPopulationFinalAdd = 11024,

        /// <summary>
        /// 人口上限FP
        /// </summary>
        MaxPopulationFinalPct = 11025,

    }
}
