
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbBulletRow : BeanBase
    {
        public TbBulletRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            HorSpeed = _buf.ReadInt();
            ControlFactor = _buf.ReadInt();
            ControlHeight = _buf.ReadInt();
            Life = _buf.ReadInt();
            EffectGroupId = _buf.ReadInt();
            ResourceId = _buf.ReadInt();
            ResourceId_Ref = null;
            FinishEffectId = _buf.ReadInt();

            PostInit();
        }

        public static TbBulletRow DeserializeTbBulletRow(ByteBuf _buf)
        {
            return new TbBulletRow(_buf);
        }

        /// <summary>
        /// 编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 水平速度
        /// </summary>
        public readonly int HorSpeed;

        /// <summary>
        /// 控制点万分比
        /// </summary>
        public readonly int ControlFactor;

        /// <summary>
        /// 控制点高度
        /// </summary>
        public readonly int ControlHeight;

        /// <summary>
        /// 生存时间
        /// </summary>
        public readonly int Life;

        /// <summary>
        /// 效果组ID
        /// </summary>
        public readonly int EffectGroupId;

        /// <summary>
        /// 子弹资源ID
        /// </summary>
        public readonly int ResourceId;

        public TbSkillResourceRow ResourceId_Ref { get; private set; }

        /// <summary>
        /// 结束特效ID
        /// </summary>
        public readonly int FinishEffectId;


        public const int __ID__ = 568834698;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            ResourceId_Ref = TbSkillResource.Instance.GetOrDefault(ResourceId);
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "name:" + Name + ","
            + "horSpeed:" + HorSpeed + ","
            + "controlFactor:" + ControlFactor + ","
            + "controlHeight:" + ControlHeight + ","
            + "life:" + Life + ","
            + "effectGroupId:" + EffectGroupId + ","
            + "resourceId:" + ResourceId + ","
            + "finishEffectId:" + FinishEffectId + ","
            + "}";
        }

        partial void PostInit();
    }
}
