
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 效果表
    /// </summary>
    [Config]
    public partial class TbEffect : Singleton<TbEffect>, IConfig
    {
        private readonly Dictionary<int, TbEffectRow> _dataMap;
        private readonly List<TbEffectRow> _dataList;

        public TbEffect(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbEffectRow>();
            _dataList = new List<TbEffectRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbEffectRow _v;
                _v = TbEffectRow.DeserializeTbEffectRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbEffectRow> DataMap => _dataMap;
        public List<TbEffectRow> DataList => _dataList;

        public TbEffectRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbEffectRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
