
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 英雄表
    /// </summary>
    [Config]
    public partial class TbHero : Singleton<TbHero>, IConfig
    {
        private readonly Dictionary<int, TbHeroRow> _dataMap;
        private readonly List<TbHeroRow> _dataList;

        public TbHero(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbHeroRow>();
            _dataList = new List<TbHeroRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbHeroRow _v;
                _v = TbHeroRow.DeserializeTbHeroRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbHeroRow> DataMap => _dataMap;
        public List<TbHeroRow> DataList => _dataList;

        public TbHeroRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbHeroRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
