
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbItemRow : BeanBase
    {
        public TbItemRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Desc = _buf.ReadString();
            Model = _buf.ReadInt();
            Model_Ref = null;
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);PricePlacement = new System.Collections.Generic.Dictionary<NumericType, int>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { NumericType _k0;  _k0 = (NumericType)_buf.ReadInt(); int _v0;  _v0 = _buf.ReadInt();     PricePlacement.Add(_k0, _v0);}}
            EffectGroupId = _buf.ReadInt();
            SearchTarget = _buf.ReadInt();
            SearchTarget_Ref = null;

            PostInit();
        }

        public static TbItemRow DeserializeTbItemRow(ByteBuf _buf)
        {
            return new TbItemRow(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 说明
        /// </summary>
        public readonly string Desc;

        /// <summary>
        /// 模型
        /// </summary>
        public readonly int Model;

        public TbResourceRow Model_Ref { get; private set; }

        /// <summary>
        /// 放置消耗类型
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<NumericType, int> PricePlacement;

        /// <summary>
        /// 效果组ID
        /// </summary>
        public readonly int EffectGroupId;

        /// <summary>
        /// 目标搜索
        /// </summary>
        public readonly int SearchTarget;

        public TbSearchRow SearchTarget_Ref { get; private set; }


        public const int __ID__ = 1275247449;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            Model_Ref = TbResource.Instance.GetOrDefault(Model);
            
            
            SearchTarget_Ref = TbSearch.Instance.GetOrDefault(SearchTarget);
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "desc:" + Desc + ","
            + "model:" + Model + ","
            + "pricePlacement:" + Luban.StringUtil.CollectionToString(PricePlacement) + ","
            + "effectGroupId:" + EffectGroupId + ","
            + "searchTarget:" + SearchTarget + ","
            + "}";
        }

        partial void PostInit();
    }
}
