
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbResourceRow : BeanBase
    {
        public TbResourceRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Url = _buf.ReadString();

            PostInit();
        }

        public static TbResourceRow DeserializeTbResourceRow(ByteBuf _buf)
        {
            return new TbResourceRow(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        ///  资源路径
        /// </summary>
        public readonly string Url;


        public const int __ID__ = -503417986;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Url:" + Url + ","
            + "}";
        }

        partial void PostInit();
    }
}
