
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 目标搜索表
    /// </summary>
    [Config]
    public partial class TbSearch : Singleton<TbSearch>, IConfig
    {
        private readonly Dictionary<int, TbSearchRow> _dataMap;
        private readonly List<TbSearchRow> _dataList;

        public TbSearch(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbSearchRow>();
            _dataList = new List<TbSearchRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbSearchRow _v;
                _v = TbSearchRow.DeserializeTbSearchRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbSearchRow> DataMap => _dataMap;
        public List<TbSearchRow> DataList => _dataList;

        public TbSearchRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbSearchRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
