
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbSkillResourceRow : BeanBase
    {
        public TbSkillResourceRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Resource = _buf.ReadInt();
            Resource_Ref = null;
            SoundId = _buf.ReadInt();
            SoundId_Ref = null;
            BindPointType = (EBindPointType)_buf.ReadInt();

            PostInit();
        }

        public static TbSkillResourceRow DeserializeTbSkillResourceRow(ByteBuf _buf)
        {
            return new TbSkillResourceRow(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 资源位置
        /// </summary>
        public readonly int Resource;

        public TbResourceRow Resource_Ref { get; private set; }

        /// <summary>
        /// 音效ID
        /// </summary>
        public readonly int SoundId;

        public TbResourceRow SoundId_Ref { get; private set; }

        /// <summary>
        /// 挂点类型
        /// </summary>
        public readonly EBindPointType BindPointType;


        public const int __ID__ = 1091878537;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            Resource_Ref = TbResource.Instance.GetOrDefault(Resource);
            SoundId_Ref = TbResource.Instance.GetOrDefault(SoundId);
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "name:" + Name + ","
            + "resource:" + Resource + ","
            + "soundId:" + SoundId + ","
            + "bindPointType:" + BindPointType + ","
            + "}";
        }

        partial void PostInit();
    }
}
