
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbSkillTrackRow : BeanBase
    {
        public TbSkillTrackRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            HorSpeed = _buf.ReadInt();
            VerSpeed = _buf.ReadInt();
            TowardType = (ESkillTrackTowardType)_buf.ReadInt();

            PostInit();
        }

        public static TbSkillTrackRow DeserializeTbSkillTrackRow(ByteBuf _buf)
        {
            return new TbSkillTrackRow(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 水平速度
        /// </summary>
        public readonly int HorSpeed;

        /// <summary>
        /// 垂直速度
        /// </summary>
        public readonly int VerSpeed;

        /// <summary>
        /// 朝向类型
        /// </summary>
        public readonly ESkillTrackTowardType TowardType;


        public const int __ID__ = 2078102034;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "name:" + Name + ","
            + "horSpeed:" + HorSpeed + ","
            + "verSpeed:" + VerSpeed + ","
            + "towardType:" + TowardType + ","
            + "}";
        }

        partial void PostInit();
    }
}
