
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbSkillBulletRow : BeanBase
    {
        public TbSkillBulletRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Life = _buf.ReadInt();
            EffectGroupId = _buf.ReadInt();
            TrackId = _buf.ReadInt();
            EffectId = _buf.ReadInt();
            FinishEffectId = _buf.ReadInt();

            PostInit();
        }

        public static TbSkillBulletRow DeserializeTbSkillBulletRow(ByteBuf _buf)
        {
            return new TbSkillBulletRow(_buf);
        }

        /// <summary>
        /// 编号
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 生存时间
        /// </summary>
        public readonly int Life;

        /// <summary>
        /// 效果组ID
        /// </summary>
        public readonly int EffectGroupId;

        /// <summary>
        /// 轨迹ID
        /// </summary>
        public readonly int TrackId;

        /// <summary>
        /// 特效ID
        /// </summary>
        public readonly int EffectId;

        /// <summary>
        /// 结束特效ID
        /// </summary>
        public readonly int FinishEffectId;


        public const int __ID__ = 530271317;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "name:" + Name + ","
            + "life:" + Life + ","
            + "effectGroupId:" + EffectGroupId + ","
            + "trackId:" + TrackId + ","
            + "effectId:" + EffectId + ","
            + "finishEffectId:" + FinishEffectId + ","
            + "}";
        }

        partial void PostInit();
    }
}
