
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 子弹表
    /// </summary>
    [Config]
    public partial class TbSkillBullet : Singleton<TbSkillBullet>, IConfig
    {
        private readonly Dictionary<int, TbSkillBulletRow> _dataMap;
        private readonly List<TbSkillBulletRow> _dataList;

        public TbSkillBullet(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbSkillBulletRow>();
            _dataList = new List<TbSkillBulletRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbSkillBulletRow _v;
                _v = TbSkillBulletRow.DeserializeTbSkillBulletRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbSkillBulletRow> DataMap => _dataMap;
        public List<TbSkillBulletRow> DataList => _dataList;

        public TbSkillBulletRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbSkillBulletRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
