
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 技能相关资源表
    /// </summary>
    [Config]
    public partial class TbSkillResource : Singleton<TbSkillResource>, IConfig
    {
        private readonly Dictionary<int, TbSkillResourceRow> _dataMap;
        private readonly List<TbSkillResourceRow> _dataList;

        public TbSkillResource(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbSkillResourceRow>();
            _dataList = new List<TbSkillResourceRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbSkillResourceRow _v;
                _v = TbSkillResourceRow.DeserializeTbSkillResourceRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbSkillResourceRow> DataMap => _dataMap;
        public List<TbSkillResourceRow> DataList => _dataList;

        public TbSkillResourceRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbSkillResourceRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
