
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 目标搜索表
    /// </summary>
    [Config]
    public partial class TbSkillSearch : Singleton<TbSkillSearch>, IConfig
    {
        private readonly Dictionary<int, TbSkillSearchRow> _dataMap;
        private readonly List<TbSkillSearchRow> _dataList;

        public TbSkillSearch(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbSkillSearchRow>();
            _dataList = new List<TbSkillSearchRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbSkillSearchRow _v;
                _v = TbSkillSearchRow.DeserializeTbSkillSearchRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbSkillSearchRow> DataMap => _dataMap;
        public List<TbSkillSearchRow> DataList => _dataList;

        public TbSkillSearchRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbSkillSearchRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
