
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbSoldierRow : BeanBase
    {
        public TbSoldierRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Level = _buf.ReadInt();
            Model = _buf.ReadInt();
            Model_Ref = null;
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Props = new System.Collections.Generic.Dictionary<NumericType, int>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { NumericType _k0;  _k0 = (NumericType)_buf.ReadInt(); int _v0;  _v0 = _buf.ReadInt();     Props.Add(_k0, _v0);}}
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Skills = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Skills[__index0] = __e0;}}
            RandomBagId = _buf.ReadInt();
            RandomBagId_Ref = null;

            PostInit();
        }

        public static TbSoldierRow DeserializeTbSoldierRow(ByteBuf _buf)
        {
            return new TbSoldierRow(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 等级
        /// </summary>
        public readonly int Level;

        /// <summary>
        /// 模型
        /// </summary>
        public readonly int Model;

        public TbResourceRow Model_Ref { get; private set; }

        /// <summary>
        /// 属性类型
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<NumericType, int> Props;

        /// <summary>
        /// 技能
        /// </summary>
        public readonly int[] Skills;

        /// <summary>
        /// 死亡掉落包
        /// </summary>
        public readonly int RandomBagId;

        public TbRandomBagRow RandomBagId_Ref { get; private set; }


        public const int __ID__ = 959563302;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            Model_Ref = TbResource.Instance.GetOrDefault(Model);
            
            
            RandomBagId_Ref = TbRandomBag.Instance.GetOrDefault(RandomBagId);
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "level:" + Level + ","
            + "model:" + Model + ","
            + "props:" + Luban.StringUtil.CollectionToString(Props) + ","
            + "skills:" + Luban.StringUtil.CollectionToString(Skills) + ","
            + "randomBagId:" + RandomBagId + ","
            + "}";
        }

        partial void PostInit();
    }
}
