
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 战斗关卡表
    /// </summary>
    [Config]
    public partial class TbStage : Singleton<TbStage>, IConfig
    {
        private readonly Dictionary<int, TbStageRow> _dataMap;
        private readonly List<TbStageRow> _dataList;

        public TbStage(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbStageRow>();
            _dataList = new List<TbStageRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbStageRow _v;
                _v = TbStageRow.DeserializeTbStageRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbStageRow> DataMap => _dataMap;
        public List<TbStageRow> DataList => _dataList;

        public TbStageRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbStageRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
