
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 弹道轨迹表
    /// </summary>
    [Config]
    public partial class TbTrack : Singleton<TbTrack>, IConfig
    {
        private readonly Dictionary<int, TbTrackRow> _dataMap;
        private readonly List<TbTrackRow> _dataList;

        public TbTrack(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbTrackRow>();
            _dataList = new List<TbTrackRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbTrackRow _v;
                _v = TbTrackRow.DeserializeTbTrackRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbTrackRow> DataMap => _dataMap;
        public List<TbTrackRow> DataList => _dataList;

        public TbTrackRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbTrackRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
