
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 机关表
    /// </summary>
    [Config]
    public partial class TbTrap : Singleton<TbTrap>, IConfig
    {
        private readonly Dictionary<int, TbTrapRow> _dataMap;
        private readonly List<TbTrapRow> _dataList;

        public TbTrap(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbTrapRow>();
            _dataList = new List<TbTrapRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbTrapRow _v;
                _v = TbTrapRow.DeserializeTbTrapRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbTrapRow> DataMap => _dataMap;
        public List<TbTrapRow> DataList => _dataList;

        public TbTrapRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbTrapRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
