
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 队伍类型
    /// </summary>
    [System.Flags]
    public enum TeamType
    {
        None = 0,

        /// <summary>
        /// 队伍A
        /// </summary>
        TeamA = 1,

        /// <summary>
        /// 队伍B
        /// </summary>
        TeamB = 2,

        /// <summary>
        /// 中立
        /// </summary>
        TeamNeutral = 4,

    }
}
