
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 资源挂点类型
    /// </summary>
    public enum EBindPointType
    {
        /// <summary>
        /// 受击点
        /// </summary>
        ATTACH = 0,

        /// <summary>
        /// 头部
        /// </summary>
        HEAD = 1,

    }
}
