
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 条件组完成类型
    /// </summary>
    public enum EGroupCompletedType
    {
        /// <summary>
        /// 无
        /// </summary>
        NONE = 0,

        /// <summary>
        /// 满足所有条件
        /// </summary>
        ALL = 1,

        /// <summary>
        /// 满足任一条件
        /// </summary>
        ANY = 2,

    }
}
