
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 索敌优先级
    /// </summary>
    public enum ESearchTargetPriority
    {
        None = 0,

        /// <summary>
        /// 最近距离
        /// </summary>
        MinDistance = 1,

        /// <summary>
        /// 最远距离
        /// </summary>
        MaxDistance = 2,

        /// <summary>
        /// 随机
        /// </summary>
        Random = 3,

    }
}
