
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 索敌类型
    /// </summary>
    public enum ESearchTargetTeam
    {
        None = 0,

        /// <summary>
        /// 自己
        /// </summary>
        SingleSelf = 1,

        /// <summary>
        /// 己方队伍
        /// </summary>
        Self = 2,

        /// <summary>
        /// 敌方队伍
        /// </summary>
        Enemy = 3,

        /// <summary>
        /// 非敌队伍
        /// </summary>
        NotEnemy = 4,

        /// <summary>
        /// 反击
        /// </summary>
        Counter = 5,

        /// <summary>
        /// 全体
        /// </summary>
        All = 6,

    }
}
