
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// BUFF类型
    /// </summary>
    public enum ESkillBuffType
    {
        NONE = 0,

        /// <summary>
        /// 增益
        /// </summary>
        BUFF = 1,

        /// <summary>
        /// 减益
        /// </summary>
        DEBUFF = 2,

        /// <summary>
        /// 控制
        /// </summary>
        CONTROL = 3,

        /// <summary>
        /// 减速
        /// </summary>
        SLOW = 4,

    }
}
