
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 效果类型
    /// </summary>
    public enum ESkillEffectType
    {
        NONE = 0,

        /// <summary>
        /// 属性改变
        /// </summary>
        CHANGE_PROPERTY = 1,

        /// <summary>
        /// 动态属性改变
        /// </summary>
        CHANGE_PROPERTY_DYNAMIC = 2,

        /// <summary>
        /// 状态改变
        /// </summary>
        CHANGE_STATE = 3,

        /// <summary>
        /// 普通攻击
        /// </summary>
        ATTACK = 4,

        /// <summary>
        /// 添加Buff
        /// </summary>
        ADD_BUFF = 5,

        /// <summary>
        /// 添加子弹
        /// </summary>
        ADD_BULLET = 6,

        /// <summary>
        /// 添加限制
        /// </summary>
        ADD_RESTRICT = 7,

        /// <summary>
        /// 随机生成种子
        /// </summary>
        ADD_SEED = 8,

        /// <summary>
        /// 移除Buff
        /// </summary>
        REMOVE_BUFF = 9,

        /// <summary>
        /// 召唤士兵
        /// </summary>
        SUMMON_SOLDIER = 10,

        /// <summary>
        /// 生产掉落
        /// </summary>
        GEN_DROP = 11,

        /// <summary>
        /// 重新索敌
        /// </summary>
        RESEARCH = 12,

        /// <summary>
        /// 掉落ID，掉落数量，[中心点坐标,size]
        /// </summary>
        RANDOM_GEN_DROP = 13,

    }
}
