
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 技能类型
    /// </summary>
    public enum ESkillType
    {
        /// <summary>
        /// 无类型
        /// </summary>
        None = 0,

        /// <summary>
        /// 普通攻击
        /// </summary>
        Normal = 1,

        /// <summary>
        /// 主动技能
        /// </summary>
        Active = 2,

        /// <summary>
        /// 死亡技能
        /// </summary>
        Dead = 3,

        /// <summary>
        /// 反击技能
        /// </summary>
        Counter = 4,

        /// <summary>
        /// CD技能
        /// </summary>
        CountDown = 5,

    }
}
