
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// BUFF类型
    /// </summary>
    public enum ESkillBuffType
    {
        None = 0,

        /// <summary>
        /// 增益
        /// </summary>
        Buff = 1,

        /// <summary>
        /// 减益
        /// </summary>
        Debuff = 2,

        /// <summary>
        /// 控制
        /// </summary>
        Control = 3,

        /// <summary>
        /// 减速
        /// </summary>
        Slow = 4,

    }
}
