
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 朝向类型
    /// </summary>
    public enum ESkillTrackTowardType
    {
        NONE = 0,

        /// <summary>
        /// 固定朝向
        /// </summary>
        DIRECTION = 1,

        /// <summary>
        /// 固定位置
        /// </summary>
        POSITION = 2,

    }
}
