
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// BUFF叠加类型
    /// </summary>
    public enum ESkillBuffOverlapType
    {
        /// <summary>
        /// 唯一
        /// </summary>
        UNIQUE = 0,

        /// <summary>
        /// 分散
        /// </summary>
        DISPERSIVE = 1,

        /// <summary>
        /// 集中
        /// </summary>
        CONCENTRATED = 2,

    }
}
