
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 实体类型
    /// </summary>
    [System.Flags]
    public enum EUnitType
    {
        None = 0,

        /// <summary>
        /// 英雄
        /// </summary>
        Hero = 1,

        /// <summary>
        /// 地块
        /// </summary>
        Block = 2,

        /// <summary>
        /// 建筑
        /// </summary>
        Building = 4,

        /// <summary>
        /// 士兵
        /// </summary>
        Soldier = 8,

        /// <summary>
        /// 掉落
        /// </summary>
        Drop = 16,

        /// <summary>
        /// 子弹
        /// </summary>
        Bullet = 32,

        /// <summary>
        /// 全局
        /// </summary>
        Global = 64,

        /// <summary>
        /// 队伍
        /// </summary>
        Team = 128,

    }
}
