
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 战斗模式
    /// </summary>
    public enum FightMode
    {
        None = 0,

        /// <summary>
        /// 玩家和电脑
        /// </summary>
        PVE = 1,

        /// <summary>
        /// 玩家和玩家
        /// </summary>
        PVP = 2,

    }
}
