
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    /// <summary>
    /// Item数量信息
    /// </summary>
    [EnableClass]
    public sealed partial class ItemCount : BeanBase
    {
        public ItemCount(ByteBuf _buf)
        {
            Type = (EUnitType)_buf.ReadInt();
            Id = _buf.ReadInt();
            Count = _buf.ReadInt();

            PostInit();
        }

        public static ItemCount DeserializeItemCount(ByteBuf _buf)
        {
            return new ItemCount(_buf);
        }

        /// <summary>
        /// 物品类型
        /// </summary>
        public readonly EUnitType Type;

        /// <summary>
        /// 配置ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 数量
        /// </summary>
        public readonly int Count;


        public const int __ID__ = -163186276;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "type:" + Type + ","
            + "id:" + Id + ","
            + "count:" + Count + ","
            + "}";
        }

        partial void PostInit();
    }
}
