
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    /// <summary>
    /// 掉落包Item
    /// </summary>
    [EnableClass]
    public sealed partial class ItemRandomBag : BeanBase
    {
        public ItemRandomBag(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Weight = _buf.ReadInt();
            Count = _buf.ReadInt();

            PostInit();
        }

        public static ItemRandomBag DeserializeItemRandomBag(ByteBuf _buf)
        {
            return new ItemRandomBag(_buf);
        }

        /// <summary>
        /// 掉落组ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 权重
        /// </summary>
        public readonly int Weight;

        /// <summary>
        /// 数量
        /// </summary>
        public readonly int Count;


        public const int __ID__ = -2022056366;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "weight:" + Weight + ","
            + "count:" + Count + ","
            + "}";
        }

        partial void PostInit();
    }
}
