
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbBuildingRow : BeanBase
    {
        public TbBuildingRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Model = _buf.ReadInt();
            Model_Ref = null;
            Radius = _buf.ReadInt();
            PlacedLayer = _buf.ReadInt();
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Shape = new bool[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { bool __e0;__e0 = _buf.ReadBool(); Shape[__index0] = __e0;}}
            CanBeAttack = _buf.ReadBool();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Props = new System.Collections.Generic.Dictionary<NumericType, int>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { NumericType _k0;  _k0 = (NumericType)_buf.ReadInt(); int _v0;  _v0 = _buf.ReadInt();     Props.Add(_k0, _v0);}}
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Skills = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Skills[__index0] = __e0;}}
            ProductSkill = _buf.ReadInt();
            ProductSkill_Ref = null;
            RandomBagId = _buf.ReadInt();
            RandomBagId_Ref = null;

            PostInit();
        }

        public static TbBuildingRow DeserializeTbBuildingRow(ByteBuf _buf)
        {
            return new TbBuildingRow(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 模型
        /// </summary>
        public readonly int Model;

        public TbResourceRow Model_Ref { get; private set; }

        /// <summary>
        /// 半径
        /// </summary>
        public readonly int Radius;

        /// <summary>
        /// 放置目标层
        /// </summary>
        public readonly int PlacedLayer;

        /// <summary>
        /// 放置形状
        /// </summary>
        public readonly bool[] Shape;

        /// <summary>
        /// 是否受攻击
        /// </summary>
        public readonly bool CanBeAttack;

        /// <summary>
        /// 属性类型
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<NumericType, int> Props;

        /// <summary>
        /// 技能
        /// </summary>
        public readonly int[] Skills;

        /// <summary>
        /// 生产技能
        /// </summary>
        public readonly int ProductSkill;

        public TbSkillRow ProductSkill_Ref { get; private set; }

        /// <summary>
        /// 死亡掉落包
        /// </summary>
        public readonly int RandomBagId;

        public TbRandomBagRow RandomBagId_Ref { get; private set; }


        public const int __ID__ = 1139858200;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            Model_Ref = TbResource.Instance.GetOrDefault(Model);
            
            
            
            
            
            
            ProductSkill_Ref = TbSkill.Instance.GetOrDefault(ProductSkill);
            RandomBagId_Ref = TbRandomBag.Instance.GetOrDefault(RandomBagId);
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "model:" + Model + ","
            + "radius:" + Radius + ","
            + "placedLayer:" + PlacedLayer + ","
            + "shape:" + Luban.StringUtil.CollectionToString(Shape) + ","
            + "canBeAttack:" + CanBeAttack + ","
            + "props:" + Luban.StringUtil.CollectionToString(Props) + ","
            + "skills:" + Luban.StringUtil.CollectionToString(Skills) + ","
            + "productSkill:" + ProductSkill + ","
            + "randomBagId:" + RandomBagId + ","
            + "}";
        }

        partial void PostInit();
    }
}
