
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbMapRow : BeanBase
    {
        public TbMapRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Scene = _buf.ReadInt();
            Scene_Ref = null;
            GridData = _buf.ReadString();

            PostInit();
        }

        public static TbMapRow DeserializeTbMapRow(ByteBuf _buf)
        {
            return new TbMapRow(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 场景
        /// </summary>
        public readonly int Scene;

        public TbResourceRow Scene_Ref { get; private set; }

        /// <summary>
        /// 网格数据
        /// </summary>
        public readonly string GridData;


        public const int __ID__ = -554327284;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            Scene_Ref = TbResource.Instance.GetOrDefault(Scene);
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "name:" + Name + ","
            + "scene:" + Scene + ","
            + "gridData:" + GridData + ","
            + "}";
        }

        partial void PostInit();
    }
}
