
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 随即掉落组
    /// </summary>
    [Config]
    public partial class TbRandomSet : Singleton<TbRandomSet>, IConfig
    {
        private readonly Dictionary<int, TbRandomSetRow> _dataMap;
        private readonly List<TbRandomSetRow> _dataList;

        public TbRandomSet(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbRandomSetRow>();
            _dataList = new List<TbRandomSetRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbRandomSetRow _v;
                _v = TbRandomSetRow.DeserializeTbRandomSetRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbRandomSetRow> DataMap => _dataMap;
        public List<TbRandomSetRow> DataList => _dataList;

        public TbRandomSetRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbRandomSetRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
