
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 资源配置
    /// </summary>
    [Config]
    public partial class TbResource : Singleton<TbResource>, IConfig
    {
        private readonly Dictionary<int, TbResourceRow> _dataMap;
        private readonly List<TbResourceRow> _dataList;

        public TbResource(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbResourceRow>();
            _dataList = new List<TbResourceRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbResourceRow _v;
                _v = TbResourceRow.DeserializeResourceConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbResourceRow> DataMap => _dataMap;
        public List<TbResourceRow> DataList => _dataList;

        public TbResourceRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbResourceRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
