
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 技能表
    /// </summary>
    [Config]
    public partial class TbSkill : Singleton<TbSkill>, IConfig
    {
        private readonly Dictionary<int, TbSkillRow> _dataMap;
        private readonly List<TbSkillRow> _dataList;

        public TbSkill(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbSkillRow>();
            _dataList = new List<TbSkillRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbSkillRow _v;
                _v = TbSkillRow.DeserializeTbSkillRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbSkillRow> DataMap => _dataMap;
        public List<TbSkillRow> DataList => _dataList;

        public TbSkillRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbSkillRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
