
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 士兵表
    /// </summary>
    [Config]
    public partial class TbSoldier : Singleton<TbSoldier>, IConfig
    {
        private readonly Dictionary<int, TbSoldierRow> _dataMap;
        private readonly List<TbSoldierRow> _dataList;

        public TbSoldier(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbSoldierRow>();
            _dataList = new List<TbSoldierRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbSoldierRow _v;
                _v = TbSoldierRow.DeserializeTbSoldierRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbSoldierRow> DataMap => _dataMap;
        public List<TbSoldierRow> DataList => _dataList;

        public TbSoldierRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbSoldierRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
