
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbStartSceneRow : BeanBase
    {
        public TbStartSceneRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Process = _buf.ReadInt();
            Zone = _buf.ReadInt();
            SceneType = _buf.ReadString();
            Name = _buf.ReadString();
            Port = _buf.ReadInt();

            PostInit();
        }

        public static TbStartSceneRow DeserializeTbStartSceneRow(ByteBuf _buf)
        {
            return new TbStartSceneRow(_buf);
        }

        public readonly int Id;

        public readonly int Process;

        public readonly int Zone;

        public readonly string SceneType;

        public readonly string Name;

        public readonly int Port;


        public const int __ID__ = -69226430;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Process:" + Process + ","
            + "Zone:" + Zone + ","
            + "SceneType:" + SceneType + ","
            + "Name:" + Name + ","
            + "Port:" + Port + ","
            + "}";
        }

        partial void PostInit();
    }
}
