
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class TbStartMachine : Singleton<TbStartMachine>, IConfig
    {
        private readonly Dictionary<int, TbStartMachineRow> _dataMap;
        private readonly List<TbStartMachineRow> _dataList;

        public TbStartMachine(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbStartMachineRow>();
            _dataList = new List<TbStartMachineRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbStartMachineRow _v;
                _v = TbStartMachineRow.DeserializeTbStartMachineRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbStartMachineRow> DataMap => _dataMap;
        public List<TbStartMachineRow> DataList => _dataList;

        public TbStartMachineRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbStartMachineRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
