
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbStartMachineRow : BeanBase
    {
        public TbStartMachineRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            InnerIP = _buf.ReadString();
            OuterIP = _buf.ReadString();
            WatcherPort = _buf.ReadString();

            PostInit();
        }

        public static TbStartMachineRow DeserializeTbStartMachineRow(ByteBuf _buf)
        {
            return new TbStartMachineRow(_buf);
        }

        public readonly int Id;

        public readonly string InnerIP;

        public readonly string OuterIP;

        public readonly string WatcherPort;


        public const int __ID__ = -1683730009;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "InnerIP:" + InnerIP + ","
            + "OuterIP:" + OuterIP + ","
            + "WatcherPort:" + WatcherPort + ","
            + "}";
        }

        partial void PostInit();
    }
}
