
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbStartZoneRow : BeanBase
    {
        public TbStartZoneRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            DBConnection = _buf.ReadString();
            DBName = _buf.ReadString();
            Desc = _buf.ReadString();

            PostInit();
        }

        public static TbStartZoneRow DeserializeTbStartZoneRow(ByteBuf _buf)
        {
            return new TbStartZoneRow(_buf);
        }

        public readonly int Id;

        public readonly string DBConnection;

        public readonly string DBName;

        public readonly string Desc;


        public const int __ID__ = 1712712058;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "DBConnection:" + DBConnection + ","
            + "DBName:" + DBName + ","
            + "Desc:" + Desc + ","
            + "}";
        }

        partial void PostInit();
    }
}
