
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class TbUnit : Singleton<TbUnit>, IConfig
    {
        private readonly Dictionary<int, TbUnitRow> _dataMap;
        private readonly List<TbUnitRow> _dataList;

        public TbUnit(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbUnitRow>();
            _dataList = new List<TbUnitRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbUnitRow _v;
                _v = TbUnitRow.DeserializeUnitConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbUnitRow> DataMap => _dataMap;
        public List<TbUnitRow> DataList => _dataList;

        public TbUnitRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbUnitRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
