
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 技能消耗类型
    /// </summary>
    public enum EConsumeType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,

        /// <summary>
        /// 消耗属性
        /// </summary>
        Property = 1,

        /// <summary>
        /// 消耗队伍属性
        /// </summary>
        TeamProperty = 2,

    }
}
