
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 索敌形状
    /// </summary>
    public enum ESearchTargetShape
    {
        None = 0,

        /// <summary>
        /// 圆形
        /// </summary>
        Circle = 1,

        /// <summary>
        /// 扇形
        /// </summary>
        Sector = 2,

        /// <summary>
        /// 矩形
        /// </summary>
        Rectangle = 3,

        /// <summary>
        /// 十字
        /// </summary>
        Cross = 4,

    }
}
