
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 索敌类型
    /// </summary>
    public enum ESearchTargetTeam
    {
        NONE = 0,

        /// <summary>
        /// 自己
        /// </summary>
        SINGLE_SELF = 1,

        /// <summary>
        /// 己方队伍
        /// </summary>
        SELF = 2,

        /// <summary>
        /// 敌方队伍
        /// </summary>
        ENEMY = 3,

        /// <summary>
        /// 非敌队伍
        /// </summary>
        NOT_ENEMY = 4,

        /// <summary>
        /// 反击
        /// </summary>
        COUNTER = 5,

        /// <summary>
        /// 全体
        /// </summary>
        ALL = 6,

    }
}
