
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 技能类型
    /// </summary>
    public enum ESkillType
    {
        /// <summary>
        /// 普通攻击
        /// </summary>
        NORMAL = 1,

        /// <summary>
        /// 主动技能
        /// </summary>
        ACTIVE = 2,

        /// <summary>
        /// 被动技能
        /// </summary>
        PASSIVE = 3,

        /// <summary>
        /// 武器技能
        /// </summary>
        WEAPON = 4,

        /// <summary>
        /// 坐骑技能
        /// </summary>
        MOUNT = 5,

    }
}
