
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 朝向类型
    /// </summary>
    public enum ETrackTowardType
    {
        None = 0,

        /// <summary>
        /// 固定朝向 用飞行距离模拟碰撞
        /// </summary>
        Direction = 1,

        /// <summary>
        /// 固定位置
        /// </summary>
        Position = 2,

        /// <summary>
        /// 跟随目标
        /// </summary>
        Target = 3,

        /// <summary>
        /// 固定朝向 实时碰撞检测
        /// </summary>
        Direction2 = 4,

    }
}
