
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 实体类型
    /// </summary>
    [System.Flags]
    public enum EUnitType
    {
        NONE = 0,

        /// <summary>
        /// 英雄
        /// </summary>
        HERO = 1,

        /// <summary>
        /// 建筑
        /// </summary>
        BUILDING = 2,

        /// <summary>
        /// 士兵
        /// </summary>
        SOLDIER = 4,

        /// <summary>
        /// 植物
        /// </summary>
        PLANT = 8,

        /// <summary>
        /// 掉落
        /// </summary>
        DROP = 16,

        /// <summary>
        /// 全局
        /// </summary>
        GLOBAL = 32,

    }
}
