
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 普通标签
    /// </summary>
    public enum FlagLabel
    {
        None = 0,

        /// <summary>
        /// 数量1
        /// </summary>
        Count1 = 1,

        /// <summary>
        /// 数量2
        /// </summary>
        Count2 = 2,

        /// <summary>
        /// 数量3
        /// </summary>
        Count3 = 3,

        /// <summary>
        /// 数量4
        /// </summary>
        Count4 = 4,

        /// <summary>
        /// 数量5
        /// </summary>
        Count5 = 5,

    }
}
