
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    /// <summary>
    /// Item创建位置
    /// </summary>
    [EnableClass]
    public sealed partial class ItemPosition : BeanBase
    {
        public ItemPosition(ByteBuf _buf)
        {
            X = _buf.ReadInt();
            Z = _buf.ReadInt();
            Type = (EUnitType)_buf.ReadInt();
            Id = _buf.ReadInt();
            Team = (TeamType)_buf.ReadInt();

            PostInit();
        }

        public static ItemPosition DeserializeItemPosition(ByteBuf _buf)
        {
            return new ItemPosition(_buf);
        }

        /// <summary>
        /// x位置
        /// </summary>
        public readonly int X;

        /// <summary>
        /// z位置
        /// </summary>
        public readonly int Z;

        /// <summary>
        /// 物品类型
        /// </summary>
        public readonly EUnitType Type;

        /// <summary>
        /// 配置ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 所属队伍
        /// </summary>
        public readonly TeamType Team;


        public const int __ID__ = 1540557180;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "x:" + X + ","
            + "z:" + Z + ","
            + "type:" + Type + ","
            + "id:" + Id + ","
            + "team:" + Team + ","
            + "}";
        }

        partial void PostInit();
    }
}
