
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 帧同步模式
    /// </summary>
    public enum LockStepMode
    {
        None = 0,

        /// <summary>
        /// 本地文件
        /// </summary>
        ObserverFile = 1,

        /// <summary>
        /// 在线战报
        /// </summary>
        ObserverReport = 2,

        /// <summary>
        /// 本地单机
        /// </summary>
        Local = 3,

        /// <summary>
        /// 多人联网
        /// </summary>
        Server = 4,

        /// <summary>
        /// 在线观战
        /// </summary>
        Observer = 5,

    }
}
