
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 地块表
    /// </summary>
    [Config]
    public partial class TbBlock : Singleton<TbBlock>, IConfig
    {
        private readonly Dictionary<int, TbBlockRow> _dataMap;
        private readonly List<TbBlockRow> _dataList;

        public TbBlock(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbBlockRow>();
            _dataList = new List<TbBlockRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbBlockRow _v;
                _v = TbBlockRow.DeserializeTbBlockRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbBlockRow> DataMap => _dataMap;
        public List<TbBlockRow> DataList => _dataList;

        public TbBlockRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbBlockRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
