
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 建筑表
    /// </summary>
    [Config]
    public partial class TbBuilding : Singleton<TbBuilding>, IConfig
    {
        private readonly Dictionary<int, TbBuildingRow> _dataMap;
        private readonly List<TbBuildingRow> _dataList;

        public TbBuilding(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbBuildingRow>();
            _dataList = new List<TbBuildingRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbBuildingRow _v;
                _v = TbBuildingRow.DeserializeTbBuildingRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbBuildingRow> DataMap => _dataMap;
        public List<TbBuildingRow> DataList => _dataList;

        public TbBuildingRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbBuildingRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
