
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// Buff表
    /// </summary>
    [Config]
    public partial class TbBuff : Singleton<TbBuff>, IConfig
    {
        private readonly Dictionary<int, TbBuffRow> _dataMap;
        private readonly List<TbBuffRow> _dataList;

        public TbBuff(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbBuffRow>();
            _dataList = new List<TbBuffRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbBuffRow _v;
                _v = TbBuffRow.DeserializeTbBuffRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbBuffRow> DataMap => _dataMap;
        public List<TbBuffRow> DataList => _dataList;

        public TbBuffRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbBuffRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
