
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbDropRow : BeanBase
    {
        public TbDropRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Props = new System.Collections.Generic.Dictionary<NumericType, int>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { NumericType _k0;  _k0 = (NumericType)_buf.ReadInt(); int _v0;  _v0 = _buf.ReadInt();     Props.Add(_k0, _v0);}}

            PostInit();
        }

        public static TbDropRow DeserializeTbDropRow(ByteBuf _buf)
        {
            return new TbDropRow(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 属性类型
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<NumericType, int> Props;


        public const int __ID__ = 1084762621;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "props:" + Luban.StringUtil.CollectionToString(Props) + ","
            + "}";
        }

        partial void PostInit();
    }
}
