
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbEffectRow : BeanBase
    {
        public TbEffectRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            GroupId = _buf.ReadInt();
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);SuccessConds = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); SuccessConds[__index0] = __e0;}}
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);FailureConds = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); FailureConds[__index0] = __e0;}}
            ActionType = (ESkillEffectType)_buf.ReadInt();
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ActionParam = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ActionParam[__index0] = __e0;}}

            PostInit();
        }

        public static TbEffectRow DeserializeTbEffectRow(ByteBuf _buf)
        {
            return new TbEffectRow(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 效果组ID
        /// </summary>
        public readonly int GroupId;

        /// <summary>
        /// 成功条件
        /// </summary>
        public readonly int[] SuccessConds;

        /// <summary>
        /// 失败条件
        /// </summary>
        public readonly int[] FailureConds;

        /// <summary>
        /// 操作
        /// </summary>
        public readonly ESkillEffectType ActionType;

        /// <summary>
        /// 操作参数
        /// </summary>
        public readonly int[] ActionParam;


        public const int __ID__ = 2131748763;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "name:" + Name + ","
            + "groupId:" + GroupId + ","
            + "successConds:" + Luban.StringUtil.CollectionToString(SuccessConds) + ","
            + "failureConds:" + Luban.StringUtil.CollectionToString(FailureConds) + ","
            + "actionType:" + ActionType + ","
            + "actionParam:" + Luban.StringUtil.CollectionToString(ActionParam) + ","
            + "}";
        }

        partial void PostInit();
    }
}
