
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 英雄皮肤表
    /// </summary>
    [Config]
    public partial class TbHeroSkin : Singleton<TbHeroSkin>, IConfig
    {
        private readonly Dictionary<int, TbHeroSkinRow> _dataMap;
        private readonly List<TbHeroSkinRow> _dataList;

        public TbHeroSkin(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbHeroSkinRow>();
            _dataList = new List<TbHeroSkinRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbHeroSkinRow _v;
                _v = TbHeroSkinRow.DeserializeTbHeroSkinRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbHeroSkinRow> DataMap => _dataMap;
        public List<TbHeroSkinRow> DataList => _dataList;

        public TbHeroSkinRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbHeroSkinRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
