
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbHeroSkinRow : BeanBase
    {
        public TbHeroSkinRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            HeroId = _buf.ReadInt();
            HeroId_Ref = null;
            Name = _buf.ReadString();
            Desc = _buf.ReadString();
            Model = _buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Props = new System.Collections.Generic.Dictionary<NumericType, int>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { NumericType _k0;  _k0 = (NumericType)_buf.ReadInt(); int _v0;  _v0 = _buf.ReadInt();     Props.Add(_k0, _v0);}}

            PostInit();
        }

        public static TbHeroSkinRow DeserializeTbHeroSkinRow(ByteBuf _buf)
        {
            return new TbHeroSkinRow(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 英雄ID
        /// </summary>
        public readonly int HeroId;

        public TbHeroRow HeroId_Ref { get; private set; }

        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;

        /// <summary>
        /// 模型
        /// </summary>
        public readonly int Model;

        /// <summary>
        /// 属性类型
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<NumericType, int> Props;


        public const int __ID__ = 1788731989;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            HeroId_Ref = TbHero.Instance.GetOrDefault(HeroId);
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "heroId:" + HeroId + ","
            + "name:" + Name + ","
            + "desc:" + Desc + ","
            + "model:" + Model + ","
            + "props:" + Luban.StringUtil.CollectionToString(Props) + ","
            + "}";
        }

        partial void PostInit();
    }
}
