
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbItemRow : BeanBase
    {
        public TbItemRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            EffectGroupId = _buf.ReadInt();
            SearchTarget = _buf.ReadInt();
            SearchTarget_Ref = null;

            PostInit();
        }

        public static TbItemRow DeserializeTbItemRow(ByteBuf _buf)
        {
            return new TbItemRow(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 效果组ID
        /// </summary>
        public readonly int EffectGroupId;

        /// <summary>
        /// 目标搜索
        /// </summary>
        public readonly int SearchTarget;

        public TbSearchRow SearchTarget_Ref { get; private set; }


        public const int __ID__ = 1275247449;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            SearchTarget_Ref = TbSearch.Instance.GetOrDefault(SearchTarget);
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "effectGroupId:" + EffectGroupId + ","
            + "searchTarget:" + SearchTarget + ","
            + "}";
        }

        partial void PostInit();
    }
}
