
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 物品表
    /// </summary>
    [Config]
    public partial class TbItem : Singleton<TbItem>, IConfig
    {
        private readonly Dictionary<int, TbItemRow> _dataMap;
        private readonly List<TbItemRow> _dataList;

        public TbItem(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbItemRow>();
            _dataList = new List<TbItemRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbItemRow _v;
                _v = TbItemRow.DeserializeTbItemRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbItemRow> DataMap => _dataMap;
        public List<TbItemRow> DataList => _dataList;

        public TbItemRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbItemRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
