
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbItemRow : BeanBase
    {
        public TbItemRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();

            PostInit();
        }

        public static TbItemRow DeserializeTbItemRow(ByteBuf _buf)
        {
            return new TbItemRow(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;


        public const int __ID__ = 1275247449;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "}";
        }

        partial void PostInit();
    }
}
