
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 战斗地图表
    /// </summary>
    [Config]
    public partial class TbMap : Singleton<TbMap>, IConfig
    {
        private readonly Dictionary<int, TbMapRow> _dataMap;
        private readonly List<TbMapRow> _dataList;

        public TbMap(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbMapRow>();
            _dataList = new List<TbMapRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbMapRow _v;
                _v = TbMapRow.DeserializeTbMapRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbMapRow> DataMap => _dataMap;
        public List<TbMapRow> DataList => _dataList;

        public TbMapRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbMapRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
