
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 随即掉落包
    /// </summary>
    [Config]
    public partial class TbRandomBag : Singleton<TbRandomBag>, IConfig
    {
        private readonly Dictionary<int, TbRandomBagRow> _dataMap;
        private readonly List<TbRandomBagRow> _dataList;

        public TbRandomBag(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbRandomBagRow>();
            _dataList = new List<TbRandomBagRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbRandomBagRow _v;
                _v = TbRandomBagRow.DeserializeTbRandomBagRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbRandomBagRow> DataMap => _dataMap;
        public List<TbRandomBagRow> DataList => _dataList;

        public TbRandomBagRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbRandomBagRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
