
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbSearchRow : BeanBase
    {
        public TbSearchRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            ValidForward = _buf.ReadBool();
            Range = _buf.ReadInt();
            Team = (ESearchTargetTeam)_buf.ReadInt();
            Type = (EUnitType)_buf.ReadInt();
            {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TableId = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); TableId[__index0] = __e0;}}
            Count = _buf.ReadInt();
            AddCountProp = (NumericType)_buf.ReadInt();
            Priority = (ESearchTargetPriority)_buf.ReadInt();

            PostInit();
        }

        public static TbSearchRow DeserializeTbSearchRow(ByteBuf _buf)
        {
            return new TbSearchRow(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 是否朝向过滤
        /// </summary>
        public readonly bool ValidForward;

        /// <summary>
        /// 范围
        /// </summary>
        public readonly int Range;

        /// <summary>
        /// 队伍
        /// </summary>
        public readonly ESearchTargetTeam Team;

        /// <summary>
        /// 类型
        /// </summary>
        public readonly EUnitType Type;

        /// <summary>
        /// 配置ID
        /// </summary>
        public readonly int[] TableId;

        /// <summary>
        /// 数量
        /// </summary>
        public readonly int Count;

        /// <summary>
        /// 加成数量的属性
        /// </summary>
        public readonly NumericType AddCountProp;

        /// <summary>
        /// 优先级
        /// </summary>
        public readonly ESearchTargetPriority Priority;


        public const int __ID__ = 1083650084;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "validForward:" + ValidForward + ","
            + "range:" + Range + ","
            + "team:" + Team + ","
            + "type:" + Type + ","
            + "tableId:" + Luban.StringUtil.CollectionToString(TableId) + ","
            + "count:" + Count + ","
            + "addCountProp:" + AddCountProp + ","
            + "priority:" + Priority + ","
            + "}";
        }

        partial void PostInit();
    }
}
