
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// Buff表
    /// </summary>
    [Config]
    public partial class TbSkillBuff : Singleton<TbSkillBuff>, IConfig
    {
        private readonly Dictionary<int, TbSkillBuffRow> _dataMap;
        private readonly List<TbSkillBuffRow> _dataList;

        public TbSkillBuff(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbSkillBuffRow>();
            _dataList = new List<TbSkillBuffRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbSkillBuffRow _v;
                _v = TbSkillBuffRow.DeserializeTbSkillBuffRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbSkillBuffRow> DataMap => _dataMap;
        public List<TbSkillBuffRow> DataList => _dataList;

        public TbSkillBuffRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbSkillBuffRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
