
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 效果表
    /// </summary>
    [Config]
    public partial class TbSkillEffect : Singleton<TbSkillEffect>, IConfig
    {
        private readonly Dictionary<int, TbSkillEffectRow> _dataMap;
        private readonly List<TbSkillEffectRow> _dataList;

        public TbSkillEffect(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbSkillEffectRow>();
            _dataList = new List<TbSkillEffectRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbSkillEffectRow _v;
                _v = TbSkillEffectRow.DeserializeTbSkillEffectRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbSkillEffectRow> DataMap => _dataMap;
        public List<TbSkillEffectRow> DataList => _dataList;

        public TbSkillEffectRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbSkillEffectRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
