
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// 弹道轨迹表
    /// </summary>
    [Config]
    public partial class TbSkillTrack : Singleton<TbSkillTrack>, IConfig
    {
        private readonly Dictionary<int, TbSkillTrackRow> _dataMap;
        private readonly List<TbSkillTrackRow> _dataList;

        public TbSkillTrack(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbSkillTrackRow>();
            _dataList = new List<TbSkillTrackRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbSkillTrackRow _v;
                _v = TbSkillTrackRow.DeserializeTbSkillTrackRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbSkillTrackRow> DataMap => _dataMap;
        public List<TbSkillTrackRow> DataList => _dataList;

        public TbSkillTrackRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbSkillTrackRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
