
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// IgnoreConfigAttribute
    /// </summary>
    public partial class TbStartScene4 : Singleton<TbStartScene4>, IConfig
    {
        private readonly Dictionary<int, TbStartSceneRow> _dataMap;
        private readonly List<TbStartSceneRow> _dataList;

        public TbStartScene4(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbStartSceneRow>();
            _dataList = new List<TbStartSceneRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbStartSceneRow _v;
                _v = TbStartSceneRow.DeserializeTbStartSceneRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbStartSceneRow> DataMap => _dataMap;
        public List<TbStartSceneRow> DataList => _dataList;

        public TbStartSceneRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbStartSceneRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
