
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbStartProcessRow : BeanBase
    {
        public TbStartProcessRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            MachineId = _buf.ReadInt();
            Port = _buf.ReadInt();

            PostInit();
        }

        public static TbStartProcessRow DeserializeTbStartProcessRow(ByteBuf _buf)
        {
            return new TbStartProcessRow(_buf);
        }

        public readonly int Id;

        public readonly int MachineId;

        public readonly int Port;


        public const int __ID__ = 546596479;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "MachineId:" + MachineId + ","
            + "Port:" + Port + ","
            + "}";
        }

        partial void PostInit();
    }
}
