
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    /// <summary>
    /// IgnoreConfigAttribute
    /// </summary>
    public partial class TbStartProcess4 : Singleton<TbStartProcess4>, IConfig
    {
        private readonly Dictionary<int, TbStartProcessRow> _dataMap;
        private readonly List<TbStartProcessRow> _dataList;

        public TbStartProcess4(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TbStartProcessRow>();
            _dataList = new List<TbStartProcessRow>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                TbStartProcessRow _v;
                _v = TbStartProcessRow.DeserializeTbStartProcessRow(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, TbStartProcessRow> DataMap => _dataMap;
        public List<TbStartProcessRow> DataList => _dataList;

        public TbStartProcessRow GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public TbStartProcessRow Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
