
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TbTrackRow : BeanBase
    {
        public TbTrackRow(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            HorSpeed = _buf.ReadInt();
            ControlFactor = _buf.ReadInt();
            ControlHeight = _buf.ReadInt();

            PostInit();
        }

        public static TbTrackRow DeserializeTbTrackRow(ByteBuf _buf)
        {
            return new TbTrackRow(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 水平速度
        /// </summary>
        public readonly int HorSpeed;

        /// <summary>
        /// 控制点万分比
        /// </summary>
        public readonly int ControlFactor;

        /// <summary>
        /// 控制点高度
        /// </summary>
        public readonly int ControlHeight;


        public const int __ID__ = 970967357;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "name:" + Name + ","
            + "horSpeed:" + HorSpeed + ","
            + "controlFactor:" + ControlFactor + ","
            + "controlHeight:" + ControlHeight + ","
            + "}";
        }

        partial void PostInit();
    }
}
